language: go
go:
  - 1.11.x
  - 1.12.x
  - master
env: GO111MODULE=on
services:
  - docker
addons:
  apt:
    update: true
install:
  - echo $TRAVIS_GO_VERSION
  - sudo pip install codecov
  - chmod 600 ./testdata/id_rsa
  - docker-compose up -d
  - while [ `docker-compose logs | grep -c Running` -ne 2 ]; do sleep 1; echo 'sleeping'; done;
  - sleep 10
before_script:
  - ssh -vvv bastion -F ./testdata/ssh_config hostname
  - ssh -vvv server -F ./testdata/ssh_config hostname
script:
  - make ci
after_script:
  - codecov
after_failure:
  - docker-compose logs
