version: '3'
services:
  bastion:
    image: k1low/sshd
    hostname: bastion
    ports:
      - "1022:22"
    volumes:
      - ./testdata/id_rsa.pub:/etc/authorized_keys/k1low
      - ./testdata/id_rsa.pub:/root/.ssh/authorized_keys
    environment:
      - SSH_USERS=k1low:1000:1000
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  server:
    image: k1low/sshd
    hostname: server
    volumes:
      - ./testdata/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
