name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Start SSH server
        run: |
            sudo chmod 600 ./testdata/id_rsa
            sudo chmod 600 ./testdata/id_rsa.pub
            docker-compose up -d
            while [ `docker-compose logs | grep -c 'Server listening'` -ne 4 ]; do sleep 1; echo 'sleeping'; done;
            sudo chmod 600 ./testdata/id_rsa
            sudo chmod 600 ./testdata/id_rsa.pub
            ssh -vvv bastion -F ./testdata/ssh_config hostname
            ssh -vvv server -F ./testdata/ssh_config hostname

      - name: Test
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
